// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"time"
)

type Class struct {
	ID        int
	TeacherID int
	Name      string
	Created   time.Time
	Updated   time.Time
}

type ClassQuiz struct {
	ClassID int
	QuizID  int
	Created time.Time
	Updated time.Time
}

type Question struct {
	ID       int
	QuizID   int
	Position int
	Type     QuestionType
	Data     []byte
	Created  time.Time
	Updated  time.Time
}

type QuestionSession struct {
	ID            int
	QuizSessionID int
	QuestionID    int
	Status        QuestionStatus
	Answer        string
	Created       time.Time
	Updated       time.Time
}

type Quiz struct {
	ID        int
	TeacherID int
	Title     string
	Excerpt   []byte
	Created   time.Time
	Updated   time.Time
}

type QuizSession struct {
	ID        int
	StudentID int
	QuizID    int
	Status    QuizStatus
	Created   time.Time
	Updated   time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Student struct {
	ID      int
	Name    string
	ClassID int
	Created time.Time
	Updated time.Time
}

type Teacher struct {
	ID           int
	Email        string
	Username     string
	PasswordHash string
	Created      time.Time
	Updated      time.Time
}
