// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"time"
)

type Class struct {
	ID        int64
	TeacherID int64
	Name      string
	Created   time.Time
	Updated   time.Time
}

type ClassQuiz struct {
	ClassID int64
	QuizID  int64
	Created time.Time
	Updated time.Time
}

type Question struct {
	ID        int64
	QuizID    int64
	Position  int64
	Segmented bool
	Type      string
	Json      interface{}
	Created   time.Time
	Updated   time.Time
}

type Quiz struct {
	ID        int64
	TeacherID int64
	Title     string
	Excerpt   interface{}
	Created   time.Time
	Updated   time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Student struct {
	ID      int64
	Name    string
	ClassID int64
	Created time.Time
	Updated time.Time
}

type StudentQuestionSession struct {
	ID                   int64
	StudentQuizSessionID int64
	QuestionID           int64
	Status               string
	Feedback             string
	Answer               string
	Created              time.Time
	Updated              time.Time
}

type StudentQuizSession struct {
	ID        int64
	StudentID int64
	QuizID    int64
	Status    string
	Created   time.Time
	Updated   time.Time
}

type Teacher struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
	Created      time.Time
	Updated      time.Time
}
