// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package model

import (
	"context"
	"time"
)

const addQuizToClass = `-- name: AddQuizToClass :exec

INSERT INTO class_quiz (
    quiz_id, class_id
) VALUES (
    ?, ?
)
`

type AddQuizToClassParams struct {
	QuizID  int64
	ClassID int64
}

// **********
// CLASS_QUIZ TABLE
// **********
func (q *Queries) AddQuizToClass(ctx context.Context, arg AddQuizToClassParams) error {
	_, err := q.db.ExecContext(ctx, addQuizToClass, arg.QuizID, arg.ClassID)
	return err
}

const createClass = `-- name: CreateClass :one

INSERT INTO class (
    teacher_id, name, created, updated
) VALUES (
    ?, ?, datetime("now"), datetime("now")
) RETURNING id, teacher_id, name, created, updated
`

type CreateClassParams struct {
	TeacherID int64
	Name      string
}

// **********
// CLASS TABLE
// **********
func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.TeacherID, arg.Name)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one

INSERT INTO question (
    quiz_id, position, type, data, created, updated
) VALUES (
    ?, ?, ?, ?, datetime("now"), datetime("now")
) RETURNING id, quiz_id, position, type, data, created, updated
`

type CreateQuestionParams struct {
	QuizID   int64
	Position int64
	Type     string
	Data     []byte
}

// **********
// QUESTION TABLE
// **********
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.QuizID,
		arg.Position,
		arg.Type,
		arg.Data,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Type,
		&i.Data,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one

INSERT INTO quiz (
    teacher_id, title, excerpt, created, updated
) VALUES (
    ?, ?, ?, datetime("now"), datetime("now")
) RETURNING id, teacher_id, title, excerpt, created, updated
`

type CreateQuizParams struct {
	TeacherID int64
	Title     string
	Excerpt   []byte
}

// **********
// QUIZ TABLE
// **********
func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, createQuiz, arg.TeacherID, arg.Title, arg.Excerpt)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Excerpt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one

INSERT INTO student (
    name, class_id, created, updated
) VALUES (
    ?, ?, datetime("now"), datetime("now")
) RETURNING id, name, class_id, created, updated
`

type CreateStudentParams struct {
	Name    string
	ClassID int64
}

// **********
// STUDENT TABLE
// **********
func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent, arg.Name, arg.ClassID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClassID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createStudentQuestionSession = `-- name: CreateStudentQuestionSession :one

INSERT INTO student_question_session (
    student_quiz_session_id, status, feedback, created, updated
) VALUES (
    ?, ?, ?, datetime("now"), datetime("now")
) RETURNING id, student_quiz_session_id, question_id, status, feedback, answer, created, updated
`

type CreateStudentQuestionSessionParams struct {
	StudentQuizSessionID int64
	Status               string
	Feedback             string
}

// **********
// STUDENT_QUESTION_SESSION TABLE
// **********
func (q *Queries) CreateStudentQuestionSession(ctx context.Context, arg CreateStudentQuestionSessionParams) (StudentQuestionSession, error) {
	row := q.db.QueryRowContext(ctx, createStudentQuestionSession, arg.StudentQuizSessionID, arg.Status, arg.Feedback)
	var i StudentQuestionSession
	err := row.Scan(
		&i.ID,
		&i.StudentQuizSessionID,
		&i.QuestionID,
		&i.Status,
		&i.Feedback,
		&i.Answer,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createStudentQuizSession = `-- name: CreateStudentQuizSession :one

INSERT INTO student_quiz_session (
    student_id, quiz_id, status, created, updated
) VALUES (
    ?, ?, ?, datetime("now"), datetime("now")
) RETURNING id, student_id, quiz_id, status, created, updated
`

type CreateStudentQuizSessionParams struct {
	StudentID int64
	QuizID    int64
	Status    string
}

// **********
// STUDENT_QUIZ_SESSION TABLE
// **********
func (q *Queries) CreateStudentQuizSession(ctx context.Context, arg CreateStudentQuizSessionParams) (StudentQuizSession, error) {
	row := q.db.QueryRowContext(ctx, createStudentQuizSession, arg.StudentID, arg.QuizID, arg.Status)
	var i StudentQuizSession
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.QuizID,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createTeacher = `-- name: CreateTeacher :one


INSERT INTO teacher (
    email, username, password_hash, created, updated
) VALUES (
    ?, ?, ?, datetime("now"), datetime("now")
) RETURNING id, email, username, password_hash, created, updated
`

type CreateTeacherParams struct {
	Email        string
	Username     string
	PasswordHash string
}

// Copyright 2024 Amr Ojjeh <amrojjeh@outlook.com>
// **********
// TEACHER TABLE
// **********
func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, createTeacher, arg.Email, arg.Username, arg.PasswordHash)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM class
WHERE id=?
`

func (q *Queries) DeleteClass(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClass, id)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM question
WHERE id=?
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quiz
WHERE id=?
`

func (q *Queries) DeleteQuiz(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuiz, id)
	return err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM student
WHERE id=?
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const deleteTeacher = `-- name: DeleteTeacher :exec
DELETE FROM teacher
WHERE email=?
`

func (q *Queries) DeleteTeacher(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteTeacher, email)
	return err
}

const getClass = `-- name: GetClass :one
SELECT id, teacher_id, name, created, updated FROM class
WHERE id=?
`

func (q *Queries) GetClass(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Name,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, quiz_id, position, type, data, created, updated FROM question
WHERE id=?
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Type,
		&i.Data,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, teacher_id, title, excerpt, created, updated FROM quiz
WHERE id=?
`

func (q *Queries) GetQuiz(ctx context.Context, id int64) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Excerpt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getTeacherByEmail = `-- name: GetTeacherByEmail :one
SELECT id, email, username, password_hash, created, updated FROM teacher
WHERE email=?
`

func (q *Queries) GetTeacherByEmail(ctx context.Context, email string) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, getTeacherByEmail, email)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listClassesByTeacher = `-- name: ListClassesByTeacher :many
SELECT id, teacher_id, name, created, updated FROM class
WHERE teacher_id=?
ORDER BY created
LIMIT ? OFFSET ?
`

type ListClassesByTeacherParams struct {
	TeacherID int64
	Limit     int64
	Offset    int64
}

func (q *Queries) ListClassesByTeacher(ctx context.Context, arg ListClassesByTeacherParams) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listClassesByTeacher, arg.TeacherID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Name,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuiz = `-- name: ListQuestionsByQuiz :many
SELECT id, quiz_id, position, type, data, created, updated FROM question
WHERE quiz_id=?
ORDER BY position
LIMIT ? OFFSET ?
`

type ListQuestionsByQuizParams struct {
	QuizID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListQuestionsByQuiz(ctx context.Context, arg ListQuestionsByQuizParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByQuiz, arg.QuizID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Position,
			&i.Type,
			&i.Data,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzesByClass = `-- name: ListQuizzesByClass :many
SELECT id, teacher_id, title, excerpt, q.created, q.updated, class_id, quiz_id, cq.created, cq.updated
FROM quiz AS q
INNER JOIN class_quiz AS cq ON cq.quiz_id=q.id
WHERE cq.class_id=?
LIMIT ? OFFSET ?
`

type ListQuizzesByClassParams struct {
	ClassID int64
	Limit   int64
	Offset  int64
}

type ListQuizzesByClassRow struct {
	ID        int64
	TeacherID int64
	Title     string
	Excerpt   []byte
	Created   time.Time
	Updated   time.Time
	ClassID   int64
	QuizID    int64
	Created_2 time.Time
	Updated_2 time.Time
}

func (q *Queries) ListQuizzesByClass(ctx context.Context, arg ListQuizzesByClassParams) ([]ListQuizzesByClassRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuizzesByClass, arg.ClassID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuizzesByClassRow
	for rows.Next() {
		var i ListQuizzesByClassRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Title,
			&i.Excerpt,
			&i.Created,
			&i.Updated,
			&i.ClassID,
			&i.QuizID,
			&i.Created_2,
			&i.Updated_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentedQuestionsByQuiz = `-- name: ListSegmentedQuestionsByQuiz :many
SELECT id, quiz_id, position, type, data, created, updated FROM question
WHERE quiz_id=? AND segmented=TRUE
ORDER BY position
LIMIT ? OFFSET ?
`

type ListSegmentedQuestionsByQuizParams struct {
	QuizID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListSegmentedQuestionsByQuiz(ctx context.Context, arg ListSegmentedQuestionsByQuizParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentedQuestionsByQuiz, arg.QuizID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Position,
			&i.Type,
			&i.Data,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByClass = `-- name: ListStudentsByClass :many
SELECT id, name, class_id, created, updated FROM student
WHERE class_id=?
LIMIT ? OFFSET ?
`

type ListStudentsByClassParams struct {
	ClassID int64
	Limit   int64
	Offset  int64
}

func (q *Queries) ListStudentsByClass(ctx context.Context, arg ListStudentsByClassParams) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudentsByClass, arg.ClassID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClassID,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT id, email, username, password_hash, created, updated FROM teacher
WHERE username LIKE ? AND email LIKE ?
ORDER BY email
LIMIT ? OFFSET ?
`

type ListTeachersParams struct {
	Username string
	Email    string
	Limit    int64
	Offset   int64
}

func (q *Queries) ListTeachers(ctx context.Context, arg ListTeachersParams) ([]Teacher, error) {
	rows, err := q.db.QueryContext(ctx, listTeachers,
		arg.Username,
		arg.Email,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Teacher
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeQuizFromClass = `-- name: RemoveQuizFromClass :exec
DELETE FROM class_quiz
WHERE quiz_id=? AND class_id=?
`

type RemoveQuizFromClassParams struct {
	QuizID  int64
	ClassID int64
}

func (q *Queries) RemoveQuizFromClass(ctx context.Context, arg RemoveQuizFromClassParams) error {
	_, err := q.db.ExecContext(ctx, removeQuizFromClass, arg.QuizID, arg.ClassID)
	return err
}
